# defaults file for nodejs
---
nodejs_version: 'nodejs-v10x'

nodejs_install:
  # To compile and install native addons from npm you may also need to install build tools
  - build-essential

nodejs_npm_packages: []
